
/****** Object:  Database [Oiga_DB]    Script Date: 10/27/2022 10:22:58 ******/
CREATE DATABASE [Oiga_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Oiga_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Oiga_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Oiga_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Oiga_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Oiga_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Oiga_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Oiga_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Oiga_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Oiga_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Oiga_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Oiga_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Oiga_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Oiga_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Oiga_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Oiga_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Oiga_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Oiga_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Oiga_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Oiga_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Oiga_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Oiga_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Oiga_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Oiga_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Oiga_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Oiga_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Oiga_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Oiga_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Oiga_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Oiga_DB] SET  MULTI_USER 
GO

ALTER DATABASE [Oiga_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Oiga_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Oiga_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Oiga_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Oiga_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Oiga_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Oiga_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Oiga_DB] SET  READ_WRITE 
GO

CREATE TABLE [dbo].[Courses](
	[id] [uniqueidentifier] NOT NULL,
	[name] [varchar](100) NULL,
	[creation_date] [date] NULL,
	[active] [bit] NULL,
 CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[CourseStudents](
	[id] [uniqueidentifier] NOT NULL,
	[course_id] [uniqueidentifier] NULL,
	[student_id] [uniqueidentifier] NULL,
	[grade] [int] NULL,
 CONSTRAINT [PK_CourseStudents] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CourseStudents]  WITH CHECK ADD  CONSTRAINT [FK_CourseStudents_Courses] FOREIGN KEY([course_id])
REFERENCES [dbo].[Courses] ([id])
GO

ALTER TABLE [dbo].[CourseStudents] CHECK CONSTRAINT [FK_CourseStudents_Courses]
GO

ALTER TABLE [dbo].[CourseStudents]  WITH CHECK ADD  CONSTRAINT [FK_CourseStudents_Students] FOREIGN KEY([student_id])
REFERENCES [dbo].[Students] ([id])
GO

ALTER TABLE [dbo].[CourseStudents] CHECK CONSTRAINT [FK_CourseStudents_Students]
GO

CREATE TABLE [dbo].[Evaluations](
	[id] [uniqueidentifier] NOT NULL,
	[course_student_id] [uniqueidentifier] NULL,
	[stars] [int] NULL,
	[description] [varchar](max) NULL,
	[creation_date] [date] NULL,
 CONSTRAINT [PK_Evaluations] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Evaluations]  WITH CHECK ADD  CONSTRAINT [FK_Evaluations_CourseStudents] FOREIGN KEY([course_student_id])
REFERENCES [dbo].[CourseStudents] ([id])
GO

ALTER TABLE [dbo].[Evaluations] CHECK CONSTRAINT [FK_Evaluations_CourseStudents]
GO

CREATE TABLE [dbo].[Students](
	[id] [uniqueidentifier] NOT NULL,
	[name] [varchar](100) NULL,
	[last_name] [varchar](100) NULL,
	[creation_date] [date] NULL,
	[active] [bit] NULL,
 CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


